def report_error():
    print('Error: tuple index out of range')

report_error()
